#file in python is read by file object 
#file object is used to read and write data from and to files

file = open("file.txt")

print(file.read())
file.close()


file = open("file.txt")

print(file.readline())

file.close()

#open function is used to open file "r" is used to read file
#"w" is used to write file
#file descriptor is a token, generated by the operating system
#that allows programs to do more operations with file
""""
creating a new file object and assigning it to a variable called File. 
The parameter we've passed to the open function is the name of the file we want to open. 
In this case, we're assuming the file we want to read is in the same directory as a script
 we're running but we can just as easily pass an absolute paths to open a file in a different directory.
When we open a file, like we're doing in this example, the operating system checks that we have 
permissions to access that file and then gives our code a file descriptor.
This is a token generated by the OS that allows programs to do more operations with the file.
In Python, this file descriptor is stored as an attribute of the files object.
The file object gives us a bunch of methods that we can use to operate with the file. 
Now, with this file object, we can read the contents of the file and print them to the screen."""




